### ISSUE TITLE
Kutt Integration with ShareX

### ISSUE THREAD

**Issue by xianx** [thedevs-network/kutt#67] opened 2018-06-19 02:26 UTC
Hello,

I am trying to integrate Kutt https://github.com/thedevs-network/kutt#api with shareX with Custom Short URL https://github.com/ShareX/CustomUploaders like Yourls https://github.com/ShareX/CustomUploaders/blob/master/yourls.org.sxcu 

but could not figure out how to do that and what to enter which field on Custom ShortURL making interface see the screenshot https://zdrive.techtunes.com.bd/s/JYr9qcJWk2orPC3

I have also generate API key and passed the value as Header Value of X-API-Key see the screenshot https://zdrive.techtunes.com.bd/s/N2r3bF3k6XD78PS

In debug window its showing {"error":"No target has been provided."}
https://zdrive.techtunes.com.bd/s/4MeEReQrd2TP9cX

How to integrate Kutt with ShareX properly?

**Comment by xianx** [comment] 2018-06-19 02:34
``

**Comment by Jaex** [comment] 2018-06-19 08:59
ShareX custom uploader support can supply arguments either as multi-part/data or url query. But Kutt API requires them as JSON data therefore it not gonna work like this:

```json
{
  "DestinationType": "URLShortener",
  "RequestURL": "https://kutt.it/api/url/submit",
  "Arguments": {
    "target": "$input$"
  },
  "Headers": {
    "X-API-Key": "YOUR API KEY HERE"
  }
}
```

**Comment by trgwii** [comment] 2018-06-19 14:06
Kutt technically supports urlencoded POST data as well (`key1=value1&key2=value2` in the request body), but this won't work until ShareX supports one of:
* POST with application/x-www-form-urlencoded
* POST with application/json

Closing for now!

**Comment by xianx** [comment] 2018-06-19 15:57
@Jaex how to make it work? Any solution?

**Comment by nightah** [comment] 2018-07-02 15:43
I got this working with Kutt behind an NGINXreverse proxy by modifying the location block to add the headers and elements that ShareX doesn't support.

NGINX config:
```
    location / {
        proxy_pass http://kutt:3000/;
        include /config/nginx/proxy.conf;
    }

    location /api/url/submit {
        proxy_pass http://kutt:3000;
        proxy_set_header Content-Type application/json;
        proxy_set_body $http_target;
    }
```

ShareX URL Shortener config:
```
{
  "Name": "kutt",
  "DestinationType": "URLShortener",
  "RequestURL": "https://example.com/api/url/submit",
  "Headers": {
    "X-API-Key": "yourapikeyhere",
    "Target": "{\"target\":\"$input$\"}"
  },
  "URL": "$json:shortUrl$"
}
```

**Comment by poeti8** [comment] 2018-07-02 17:43
Reopening the issue because I might add support for URL query in the future.
For now, @nightah solution should work if you have hosted this app yourself.

**Comment by xianx** [comment] 2018-07-12 18:54
Any update. We are using kutt for our team but without shareX support we are not doing day to day sharing.

**Comment by xianx** [comment] 2018-07-12 18:55
@nightah but how to make it work with custom domain? We are running self hosted Kutt and  using with custom domain behind a nGinx Proxy.

**Comment by poeti8** [comment] 2018-07-14 11:41
@xianx what's the proxy.conf though? This?
https://www.nginx.com/resources/wiki/start/topics/examples/full/#proxy-conf

**Comment by xianx** [comment] 2018-07-26 23:46
@nightah @poeti8 After adding nginx rules ShareX is working but kutt web interface is showing error and not making the url short.

When user is logged-in its showing 

"No target has been provided."

and when not logged-in showing

"reCAPTCHA is not valid. Try again."

You can see this video for clarity https://techtun.es/xPEJ5e You can also try by yourself by visiting https://techtun.es/ url.

Below is my full nginx configuration file. (Some text has been replace with sudo text for security)

````
server {

  listen 80;

  server_name domainname.com;
  include conf.d/letsencrypt.inc;
  # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
  return 301 https://$host$request_uri;

}

server {

  listen 443 ssl http2;

  ssl_certificate /etc/letsencrypt/live/domainname.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domainname.com/privkey.pem;

  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_session_tickets off;

  # Diffie-Hellman parameter for DHE ciphersuites
  ssl_dhparam /mydir/ssl/dhparam.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers "LONG Ciphers CODE";
  ssl_prefer_server_ciphers on;
  ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

  # HSTS (15768000 seconds = 6 months)
  add_header Strict-Transport-Security max-age=15768000;

  # OCSP Stapling ---
  # fetch OCSP records from URL in ssl_certificate and cache them
  ssl_stapling on;
  ssl_stapling_verify on;

  root /var/www/theapp;
  server_name domainname.com;
  index index.html;
  resolver 172.17.0.1 valid=60s ipv6=off;
  set $backend theapp;
  include conf.d/letsencrypt.inc;
  
  
  location ~ /\.git {
    deny all;
  }

  try_files $uri/index.html $uri @app;
  
  
  location @app {
    proxy_pass        http://$backend:3000;
    proxy_redirect    off;
    proxy_set_header  Upgrade $http_upgrade;
    proxy_set_header  Connection "upgrade";
    proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
  }
  
  
  location /api/url/submit {
    proxy_pass        http://$backend:3000;
    proxy_redirect    off;
    proxy_set_header  Upgrade $http_upgrade;
    proxy_set_header  Connection "upgrade";
    proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_set_header Content-Type application/json;
    proxy_set_body $http_target;
  }
 
}

````

How to make it work both for ShareX and Kutt?

Thanks in advance.

**Comment by xianx** [comment] 2018-07-27 20:04
@nightah @poeti8 Any solution to above nginx file?

**Comment by nightah** [comment] 2018-07-30 13:49
Didn't really think about the frontend app because I don't particularly use it.
You can easily fix the problem by changing your endpoint for ShareX.

```
server {

  listen 80;

  server_name domainname.com;
  include conf.d/letsencrypt.inc;
  # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
  return 301 https://$host$request_uri;

}

server {

  listen 443 ssl http2;

  ssl_certificate /etc/letsencrypt/live/domainname.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domainname.com/privkey.pem;

  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_session_tickets off;

  # Diffie-Hellman parameter for DHE ciphersuites
  ssl_dhparam /mydir/ssl/dhparam.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers "LONG Ciphers CODE";
  ssl_prefer_server_ciphers on;
  ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

  # HSTS (15768000 seconds = 6 months)
  add_header Strict-Transport-Security max-age=15768000;

  # OCSP Stapling ---
  # fetch OCSP records from URL in ssl_certificate and cache them
  ssl_stapling on;
  ssl_stapling_verify on;

  root /var/www/theapp;
  server_name domainname.com;
  index index.html;
  resolver 172.17.0.1 valid=60s ipv6=off;
  set $backend theapp;
  include conf.d/letsencrypt.inc;
  
  
  location ~ /\.git {
    deny all;
  }

  try_files $uri/index.html $uri @app;
  
  
  location @app {
    proxy_pass        http://$backend:3000;
    proxy_redirect    off;
    proxy_set_header  Upgrade $http_upgrade;
    proxy_set_header  Connection "upgrade";
    proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
  }
  
  
  location /api/url/sharex {
    proxy_pass        http://$backend:3000/api/url/submit;
    proxy_redirect    off;
    proxy_set_header  Upgrade $http_upgrade;
    proxy_set_header  Connection "upgrade";
    proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_set_header Content-Type application/json;
    proxy_set_body $http_target;
  }
 
}
```

Make sure to change your ShareX config to this:
```
{
  "Name": "kutt",
  "DestinationType": "URLShortener",
  "RequestURL": "https://example.com/api/url/sharex",
  "Headers": {
    "X-API-Key": "yourapikeyhere",
    "Target": "{\"target\":\"$input$\"}"
  },
  "URL": "$json:shortUrl$"
}
```

**Comment by poeti8** [comment] 2018-07-30 16:08
Thank you @xianx. It works fine for me.
I added a wiki page and a section in readme.
https://github.com/thedevs-network/kutt/wiki/ShareX

Closing the issue.

**Closed by poeti8** 2018-07-30 16:08 UTC
Labels: enhancement

**Comment by xianx** [comment] 2018-07-30 17:10
@poeti8 in wiki there should be hint that one need to setup Kutt behind an NGINX reverse proxy else it will not be work now as kutt do not have support for URL query to work with ShareX now. It will be added in next version but one can setup their own Kutt behind an NGINX reverse proxy and use the proxy configuration on nginx.

Thanks.

**Comment by xianx** [comment] 2018-07-30 17:33
@nightah now working both on front-end and ShareX. Thanks a lot.

**Comment by Jaex** [comment] 2018-10-02 16:28
I added Kutt support to ShareX now:

![](https://jaex.getsharex.com/2018/10/ShareX_GBe6oP2OJO.png)

I was only be able to test it with kutt.it but probably it will work same with custom hosted ones too.

**Comment by nightah** [comment] 2018-10-03 07:45
@Jaex I'd be happy to test but there's been no release since you added this. Let me know when it is and I'll give it a try.

**Comment by Jaex** [comment] 2018-10-03 11:36
You can test it like this: https://getsharex.com/docs/dev-builds

**Comment by nightah** [comment] 2018-10-03 13:07
@Jaex: I can confirm this works with custom hosted instances too.
@poeti8: You can probably change the wiki perhaps when there's a stable release of ShareX including this, no more webserver trickery required.

**Comment by MKRhere** [comment] 2018-10-06 14:31
@Jaex Does this mean ShareX now supports `application/json`?

**Comment by DananFlander** [comment] 2020-07-03 01:17
Has anyone tested using Kutt through ShareX with a custom host? I can't seem to get it to work and only get thrown kutt.it links instead of my custom danan.gg attempts.

![chrome_2020-07-02_18-14-50](https://user-images.githubusercontent.com/4238186/86421839-32187e80-bc90-11ea-9a77-8f8b1949ad1d.png)

**Comment by adx74** [comment] 2020-07-25 22:11
same problem as @DananFlander if anyone can help us please :D

**Comment by DananFlander** [comment] 2020-07-28 22:30
@nightah @Jaex send help

**Comment by Jaex** [comment] 2020-07-29 04:38
Without be able to test it I can't implement it.

**Comment by adx74** [comment] 2020-07-29 10:25
What do you need to be able to test it ?

**Comment by poeti8** [comment] 2020-07-29 10:32
@Jaex you can sign up and set domain in settings. Also Kutt now uses API v2: https://docs.kutt.it, so please use this one since v1 is deprecated.

**Comment by Jaex** [comment] 2020-07-29 10:35
I can't scroll that docs page, it keep scrolling to top automatically. (Chrome 84.0.4147.105)

**Comment by Jaex** [comment] 2020-07-29 10:40
Video showing the issue: https://jaex.getsharex.com/2020/07/zukKAvCJLv.mp4

**Comment by poeti8** [comment] 2020-07-29 10:45
I see, seems like [redoc](https://github.com/Redocly/redoc) has issues. Can you use another browser for the time being?

**Comment by Jaex** [comment] 2020-07-29 14:30
I implemented API v2 now but request fails:

```
Request URL:
https://kutt.it/api/v2/links

Status code:
(500) Internal Server Error

Response text:
{"error":"An error occurred."}
```

**Comment by poeti8** [comment] 2020-07-29 14:41
Can you send your request body here?

**Comment by Jaex** [comment] 2020-07-29 14:46
```json
{"target":"https://jaex.getsharex.com/2020/07/Tpd0TsJi3z.png","password":null,"customurl":null,"reuse":false,"domain":null}
```

**Comment by Jaex** [comment] 2020-07-29 14:54
API v2 diff: https://github.com/ShareX/ShareX/commit/f685dd177b91f61fe4bfcbdcb49e7854561ce342

**Comment by poeti8** [comment] 2020-07-29 14:55
Updated the server. Now `null` values should be allowed too. Please try again now.

**Comment by Jaex** [comment] 2020-07-29 14:58
Now it gives:

```
{"error":"Password length must be between 3 and 64."}
```

**Comment by poeti8** [comment] 2020-07-29 15:04
Seems like you're sending empty string instead of null. I updated the API again to allow empty string as well. Try now.

**Comment by Jaex** [comment] 2020-07-29 15:18
Neither from web UI or API I can't make Kutt return custom domain which starts with `https://` prefix, instead it removes prefix and returns url with `http://` prefix instead.

**Comment by Jaex** [comment] 2020-07-29 15:20
> Seems like you're sending empty string instead of null. I updated the API again to allow empty string as well. Try now.

Actually by default setting values are null but after edit password from UI then that value becomes empty string.

**Comment by poeti8** [comment] 2020-07-29 15:20
yes custom domain is `http://` only right now as we don't have the feature to add certificates to custom domains.

**Comment by Jaex** [comment] 2020-07-29 15:23
> yes custom domain is `http://` only right now as we don't have the feature to add certificates to custom domains yet.

But if I edit URL and add `https://` prefix manually, then URL opens fine. See: https://kutt.getsharex.com/6I86Qi

**Comment by poeti8** [comment] 2020-07-29 15:25
It's because you're using subdomain and hosting and handling SSL certs. Most domains in Kutt don't have certs except a few I manually added.

**Comment by Jaex** [comment] 2020-07-29 15:57
If I didn't handle SSL certs for my own domain then why would I want to use `https://` link at all with custom domain feature. So I don't get what you mean.

**Comment by poeti8** [comment] 2020-07-29 16:02
I am not sure what's your point either. In Kutt, normal links -> `https://` links with custom domain -> `http://` since Kutt is usually responsible for providing SSL certs and we don't do at the moment.

**Comment by Jaex** [comment] 2020-07-29 16:10
By the way `description` parameter is missing in API docs.

**Comment by poeti8** [comment] 2020-07-30 06:58
Thanks, added now.
