### ISSUE TITLE
Getting continuous "An unexpected error has occurred." error on both kutt.it official site also on self hosted kutt

### ISSUE THREAD

**Issue by xianx** [thedevs-network/kutt#61] opened 2018-06-17 11:00 UTC
I am getting continuous "An unexpected error has occurred." error on both kutt.it official site also on my self hosted kutt. Here is a screen cast of the error https://zdrive.techtunes.com.bd/s/fCXGWe2ZQoxic7C How to fix it?

**Comment by fredliang44** [comment] 2018-06-18 08:01
Same here, if iI refresh `https://kutt.it/` , chrome console alerts
```
main.js:1 window.grecaptcha.render is not a function
TypeError: window.grecaptcha.render is not a function
```

**Comment by xianx** [comment] 2018-06-18 11:08
here is the chrome console output https://zdrive.techtunes.com.bd/s/3XrJdPwLNiNDaZX/preview

**Comment by abhijithvijayan** [comment] 2018-06-18 14:36
Same here in some browsers

**Comment by poeti8** [comment] 2018-06-18 15:16
Seems like the problem is reCAPTCHA couldn't be loaded. Will work on it.
Also, did you disabled the JS or are you on any specific internet connection that may block the reCAPTCHA?

**Comment by poeti8** [comment] 2018-06-18 16:07
Please try again, let me know if problem is solved to close the issue.

**Comment by fredliang44** [comment] 2018-06-18 16:10
It works fine now.

**Comment by xianx** [comment] 2018-06-18 16:19
Works nice now.

**Closed** 2018-06-18 16:21 UTC
Labels: bug, question
