### ISSUE TITLE
Recaptcha nocaptcha

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#77] opened 2018-06-24 08:52 UTC
Site scrolls down to the bottom after captcha verification forcing to go to top again to see the shortened link.

**Comment by abhijithvijayan** [comment] 2018-06-24 08:58
Positioning the recaptcha to the top for the fix might help I guess

**Comment by trgwii** [comment] 2018-06-25 14:03
I can't reproduce this, it seems to work for me

**Comment by poeti8** [comment] 2018-06-25 14:05
He means if reCAPTCHA pops up it's going to take the user to the bottom of the page. I don't have a problem with that because I don't want it on top of the page. Also, I don't like the invisible captcha's badge. So it's a `wontfix` for now.

**Closed by poeti8** 2018-06-25 14:05 UTC
Labels: wontfix
