### ISSUE TITLE
Link clicks always at 0, no longer updating. (Im using custom domain)

### ISSUE THREAD

**Issue by rosswalpole** [thedevs-network/kutt#344] opened 2020-07-07 23:10 UTC
Hi all,

I have been using this for months and it was working, after integrating this service into my app using the API. I'm having to make difficult decision to move to another solution. This project seems to just be abandoned at this stage and is too un-reliable to use for any commercial purpose. I appreciate that it is free and open source.

I thought i would let you know of the issue anyway, and best of luck with the project.

Thanks,

**Comment by poeti8** [comment] 2020-07-09 15:55
Hey, the issue is fixed now. And no it's not abandoned I'm working on adding new features and fixing current issues. We're also releasing the new version of the browser extension today with new design to support custom domains and passwords.

**Closed by poeti8** 2020-07-09 15:55 UTC
